apiVersion: apps/v1
kind: Deployment
metadata:
    name: product-service

spec:
    replicas: 2
    selector:
        matchLabels:
            app: product-service
            
    template:
        metadata:
            labels:
                app: product-service
        
        spec:
            containers:                
                - name: product-service
                  image: 256664600401.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest
                  ports: 
                  - containerPort: 5000
            
            imagePullSecrets:
                - name: ecr-secret
